<?php

defined('BASEPATH') OR exit('No direct script access allowed');

$config['email_action_options'] = array(
    ''                                        => 'eMail Action',
    'new_order'                               => 'New Order',
    'cancelled_order'                         => 'Cancelled Order',
    'failed_order'                            => 'Failed Order',
    'customer_on_hold_order'                  => 'Order On-hold',
    'customer_processing_order'               => 'Supplement Processing Order',
    'customer_meal_processing_order'          => 'Meal Processing Order',
    'customer_completed_order'                => 'Completed Supplement Order',
    'customer_completed_meal_order'           => 'Completed Meal Order',
    'customer_refunded_order'                 => 'Refunded Order',
    'customer_invoice'                        => 'Customer Invoice / Order details',
    'customer_note'                           => 'Customer Supplement Note',
    'customer_meal_note'                      => 'Customer Meal Note',
    'customer_reset_password'                 => 'Reset Password',
    'customer_new_account'                    => 'New Account',
    'team_member_new_account'                 => 'Team Member New Account',
    'customer_registration'                   => 'Customer Registration',
    'renewal_order'                           => 'New Renewal Order',
    'processing_renewal_order'                => 'Processing Renewal Order',
    'processing_meal_renewal_order'           => 'Processing Meal Renewal Order',
    'completed_renewal_order'                 => 'Completed Renewal Order',
    'customer_renewal_invoice'                => 'Customer Renewal Invoice',
    'subscription_created'                    => 'Subscription Created',
    'activated_subscription'                  => 'Activated Subscription',
    'cancelled_subscription'                  => 'Cancelled Subscription',
    'cancelled_pending_subscription'          => 'Cancelled Pending Subscription',
    'on_hold_subscription'                    => 'Suspended Subscription',
    'subscription_renewal_payment_failed'     => 'Subscription Renewal Payment Failed',
    'subscription_renewal_order_failed_alert' => 'Failed Subscription Payment Alert',
    'customer_payment_retry'                  => 'Customer Payment Retry',
    'payment_retry'                           => 'Payment Retry',
    'user_feedback'                           => 'User Feedback',
    'signup_request_approved'                 => 'Sign Up Request Approved',
    'signup_request_declined'                 => 'Sign Up Request Declined',
    'distributor_payout_invoice'              => 'Distributor Payout Invoice',
    'reset_and_resend_password'               => 'Reset & Resend password',
    'coupon_payout'                           => 'Meal Commission Coupon Payout',
    'meal_purchase_coupon'                    => 'Meal Purchase Coupon',
    'meal_48_items_purchase_coupon'           => '48 Meal Purchase Coupon',
);
